# Generated by Django 5.0.6 on 2024-06-02 01:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0002_alter_student_avatar_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPMarkRemovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=12)),
                ('subject_name', models.CharField(max_length=100)),
                ('units', models.IntegerField()),
                ('sem_year', models.CharField(max_length=50)),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.student')),
            ],
        ),
    ]
