# Generated by Django 5.0.6 on 2024-06-02 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('department', '0003_alter_department_dean'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='approved_by_ACAD',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='approved_by_registrar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
