# Generated by Django 5.0.6 on 2024-06-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_ipmarkremovalrequest_dean'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipmarkremovalrequest',
            name='qr_code',
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='qr_code_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
