# Generated by Django 5.0.6 on 2024-06-04 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_ipmarkremovalrequest_qr_code_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='approved_by_dean',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='approved_by_faculty',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdditionalFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='additional_files/')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ipmarkremovalrequest')),
            ],
        ),
    ]
