# Generated by Django 5.0.6 on 2024-06-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_additionalfile_file_ipmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipmark',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
