# Generated by Django 5.0.6 on 2024-06-05 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_ipmark_date_created'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='acad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registrar', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ipmarkremovalrequest',
            name='approved_by_ACAD',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ipmarkremovalrequest',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean', to=settings.AUTH_USER_MODEL),
        ),
    ]
