# Generated by Django 5.0.6 on 2024-06-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_ipmarkremovalrequest_acad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipmarkremovalrequest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
