# Generated by Django 5.0.6 on 2024-06-10 18:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_date_created_student_date_created'),
        ('base', '0011_ipmarkremovalrequest_date_updated'),
        ('department', '0003_alter_department_dean'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLeaveOfAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lengthOfService', models.CharField(max_length=50)),
                ('purpose', models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Official Business', 'Official Business'), ('Other', 'Other')], max_length=50)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('number_of_days', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('is_there_substitute', models.BooleanField(default=False)),
                ('reason_for_substitute', models.TextField(blank=True, null=True)),
                ('approved_by_dean', models.BooleanField(default=False)),
                ('approved_by_ACAD', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_requested', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('acad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acad_fac', to=settings.AUTH_USER_MODEL)),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean_fac', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
            ],
        ),
    ]
