# Generated by Django 5.0.6 on 2024-06-12 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_facultyleaveofabsence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyleaveofabsence',
            name='approved_by_HR',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyleaveofabsence',
            name='hr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr_fac', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facultyleaveofabsence',
            name='purpose',
            field=models.CharField(choices=[('Sick Leave', 'Sick Leave'), ('Vacation Leave', 'Vacation Leave'), ('Official Business', 'Official Business')], max_length=50),
        ),
    ]
