# Generated by Django 5.0.6 on 2024-06-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_facultyleaveofabsence_approved_by_hr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyleaveofabsence',
            name='name_of_sustitute',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
