# Generated by Django 5.0.6 on 2024-06-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_facultyleaveofabsence_name_of_sustitute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultyleaveofabsence',
            old_name='name_of_sustitute',
            new_name='name_of_substitute',
        ),
    ]
