# Generated by Django 5.0.6 on 2024-06-13 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_employee_date_created_student_date_created'),
        ('base', '0015_rename_name_of_sustitute_facultyleaveofabsence_name_of_substitute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('subject_code', models.CharField(max_length=12)),
                ('year', models.CharField(max_length=15)),
                ('semester', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='files/')),
                ('approved_by_dean', models.BooleanField(default=False)),
                ('approved_by_ACAD', models.BooleanField(default=False)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('acad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acad_cg', to=settings.AUTH_USER_MODEL)),
                ('dean', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dean_cg', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.employee')),
            ],
        ),
    ]
