# Generated by Django 5.0.6 on 2024-06-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_department_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='files/')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
