# Generated by Django 5.0.6 on 2024-06-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_files'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
